version: "3"
services:
    phpmemcachedadmin:
        image: "php:7.4.33-apache"
        volumes:
            - "./:/var/www/"
            - "./docker/apache2/000-default.conf:/etc/apache2/sites-enabled/000-default.conf:ro"
        ports:
            - "80:80"
