version: "3"

services:
  phpmemcachedadmin:
    container_name: 'phpmemcachedadmin'
    build:
      dockerfile: ./docker/images/php/Dockerfile
      context: ./
      args:
        - BUILDKIT_INLINE_CACHE=1
    tty: true
    ports:
      - '8080:80'
    restart: unless-stopped
    environment:
      - 'TZ=UTC'
      - 'COMPOSE_CONVERT_WINDOWS_PATHS=1'
    volumes:
      - './app/:/app/'
    networks:
      - network1

networks:
  network1:
    driver: bridge
