version: "3"
services:
    phpmemcachedadmin:
        image: "alphayax/phpmemcachedadmin"
        volumes:
            - "./:/var/www/"
            - "./src:/var/www/html"
        ports:
            - "80:80"
